version: '2'
services:
  postgres:
    image: 'postgres:9.6'
    environment:
      POSTGRES_USER: 'athena'
      POSTGRES_PASSWORD: 'athena123'
    ports:
      - '5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  skipgram:
    image: anonoz/fyp-skipgram:0.0.1
    ports:
      - '6001'

  dbow:
    image: anonoz/fyp-dbow:0.0.1
    ports:
      - '6002'

  web:
    build: .
    command: foreman start
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - skipgram
      - dbow
    links:
      - "postgres"
      - "redis"
      - "skipgram"
      - "dbow"
    environment:
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgres://athena:athena123@postgres/athena
      LSTM_URL: http://skipgram:6001
      HANZO_URL: http://skipgram:6001
      GRU_URL: http://skipgram:6001
      FFNN_URL: http://dbow:6002
      SVM_URL: http://dbow:6002
      RF_URL: http://dbow:6002
      GENJI_URL: http://skipgram:6001

volumes:
  redis:
  postgres:
